### ISSUE TITLE
Does not work with new TFC Drift Detection capability

### ISSUE THREAD

**Issue by jstaffin-presidio** [gitrgoliveira/vault-plugin-auth-tfe#6]
The drift detection capability generates runs that pass a state of "applied" and as such the plugin rejects the login.  

Here is a log message from a denied login from an attempt triggered by the drift detection on a workspace

login unauthorized due to: Run ID run-zDuNmMvbfmPyRGdS status is applied. Expected planning or applying: timestamp=2022-08-10T20:25:58.257Z

**Comment by jstaffin-presidio** [comment]
https://github.com/gitrgoliveira/vault-plugin-auth-tfe/blob/e7d056eb065691875c13348b44227d37be30d8b0/path_login.go#L266

Appears to be where the additional state of "applied" would need to be added

**Comment by gitrgoliveira** [comment]
It seems like the run status cannot be evaluated properly under drift detection plans.
Having this check may be meaningless anyway since the Terraform token is revoked at the end of a run/plan/apply.

**Comment by gitrgoliveira** [comment]
If the latest release does not fix, please reopen the issue :-)
